# Site settings
title: Iran University of Science and Technology
course_name: Software Engineering
course_description: In this course you will learn the principles behind designing a large scale software system. The main metrics considered for the design of systems in this course is flexibility toward change and maintainability. Students will be involved in developing a software system during the semester where they will learn the complexities of working in a group, performing project management practices and exercise their knowledge regarding the development of complex software systems.
course_semester: "Fall 2019"
description: |
    Instructor: Dr.ashtiani

message: #Please register to our Google <a href="https://groups.google.com/forum/#!forum/gp-id">groups page</a> to get course notifications via email.
baseurl: "/software_engineering" # the subpath of your site, e.g. /blog/
url: "http://shahrzadazari.github.io/software_engineering/" # the base hostname & protocol for your site
syllabus: http://shahrzadazari.github.io/software_engineering/syllabus/
githubdir: 

# Author/user information
email: m_ashtiani@iust.ac.ir
number: 02173225328
#twitter_username: broken_twitter 
#github_username:  broken_github
#google_scholar_id: dsdZaDAAAAAJ&hl=en
authorurl: "http://webpages.iust.ac.ir/m_ashtiani"
address: |
    School of Computer Engineering
    Iran University of Science and Technology
    Tehran, Iran


# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false

sass:
    style: :compressed        

defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
      comments: false



plugins:
    - jekyll-jalali
